[package]
name = "shim-metadata-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
ristretto_classfile = "0.17.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
zip = "2.6.1"
