name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout Code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Set up Rust
    - name: Set up Rust (nightly)
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        components: rustc-dev llvm-tools cargo

    # 4. Set up Java
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    # 5. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # 6. Set up Gradle
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4

    # 7. make just the files needed to cargo cache
    - name: Gen Files
      run: python3 build.py gen-files
      
    # 8. Cargo Caching (Crucial for speed)
    - name: Cache cargo dependencies
      uses: Swatinem/rust-cache@v2
    
    # 9. Build using the CI-specific target
    - name: Build CI Target
      run: python3 build.py ci

    # 10. Run tests
    - name: Run integration tests (debug mode)
      run: python3 Tester.py

    # 11. Run tests in release mode
    - name: Run integration tests (release mode)
      run: python3 Tester.py --release